txt2bin, bin2bin_no_00:
	g++ -Wno-logical-op-parentheses -O2 -o txt2bin txt2bin.cpp data.cpp
	g++ -Wno-logical-op-parentheses -O2 -o bin2bin_no_00 bin2bin_no_00.cpp data.cpp
clean:
	rm -f *.o txt2bin, bin2bin_no_00
